// features/inventory/pdf/generate-low-stock-pdf.ts

import jsPDF from "jspdf"

import autoTable from "jspdf-autotable"

import { GenerateLowStockPDFInput } from "../types/low-stock.types"

type RGB = [number, number, number]

const COLORS: Record<string, RGB> = {
  primary: [15, 23, 42],

  secondary: [71, 85, 105],

  border: [226, 232, 240],

  light: [248, 250, 252],

  success: [22, 163, 74],

  warning: [234, 179, 8],

  danger: [220, 38, 38],
}

function getSeverity(current: number, minimum: number) {
  const ratio = current / minimum

  if (ratio <= 0.25) {
    return {
      label: "CRITICAL",
      color: COLORS.danger,
    }
  }

  if (ratio <= 0.5) {
    return {
      label: "WARNING",
      color: COLORS.warning,
    }
  }

  return {
    label: "LOW",
    color: COLORS.success,
  }
}

export async function generateLowStockPDF(input: GenerateLowStockPDFInput) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  })

  const generatedAt = input.generatedAt ?? new Date()

  /*
   |--------------------------------------------------------------------------
   | Background Header
   |--------------------------------------------------------------------------
   */

  doc.setFillColor(...COLORS.primary)

  doc.rect(0, 0, 210, 40, "F")

  /*
   |--------------------------------------------------------------------------
   | Company Name
   |--------------------------------------------------------------------------
   */

  doc.setTextColor(255, 255, 255)

  doc.setFont("helvetica", "bold")

  doc.setFontSize(24)

  doc.text(input.company.name, 14, 18)

  doc.setFontSize(12)

  doc.setFont("helvetica", "normal")

  doc.text("LOW STOCK PROCUREMENT REQUEST", 14, 28)

  /*
   |--------------------------------------------------------------------------
   | Meta Container
   |--------------------------------------------------------------------------
   */

  doc.setFillColor(...COLORS.light)

  doc.roundedRect(14, 48, 182, 28, 3, 3, "F")

  doc.setDrawColor(...COLORS.border)

  doc.roundedRect(14, 48, 182, 28, 3, 3)

  doc.setTextColor(0, 0, 0)

  doc.setFontSize(10)

  doc.setFont("helvetica", "bold")

  doc.text("Request ID", 20, 58)

  doc.text("Generated By", 90, 58)

  doc.text("Generated At", 150, 58)

  doc.setFont("helvetica", "normal")

  doc.setTextColor(...COLORS.secondary)

  doc.text(input.requestId, 20, 65)

  doc.text(input.generatedBy, 90, 65)

  doc.text(generatedAt.toLocaleString(), 150, 65)

  /*
   |--------------------------------------------------------------------------
   | Summary
   |--------------------------------------------------------------------------
   */

  const totalItems = input.items.length

  const criticalItems = input.items.filter(
    (item) =>
      getSeverity(item.currentStock, item.minimumStock).label === "CRITICAL"
  ).length

  doc.setFontSize(11)

  doc.setTextColor(0, 0, 0)

  doc.setFont("helvetica", "bold")

  doc.text(`Total Low Stock Items: ${totalItems}`, 14, 92)

  doc.text(`Critical Items: ${criticalItems}`, 90, 92)

  /*
   |--------------------------------------------------------------------------
   | Table
   |--------------------------------------------------------------------------
   */

  autoTable(doc, {
    startY: 100,

    head: [
      ["#", "Product", "Current", "Minimum", "Reorder", "Unit", "Severity"],
    ],

    body: input.items.map((item, index) => {
      const severity = getSeverity(item.currentStock, item.minimumStock)

      return [
        index + 1,
        item.productName,
        item.currentStock,
        item.minimumStock,
        item.reorderQuantity,
        item.unit ?? "-",
        severity.label,
      ]
    }),

    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 4,
      valign: "middle",
      textColor: [15, 23, 42],
      lineColor: COLORS.border,
      lineWidth: 0.2,
    },

    headStyles: {
      fillColor: COLORS.primary,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      halign: "center",
    },

    alternateRowStyles: {
      fillColor: COLORS.light,
    },

    bodyStyles: {
      halign: "center",
    },

    columnStyles: {
      1: {
        halign: "left",
      },
    },

    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 6) {
        const value = String(data.cell.raw)

        if (value === "CRITICAL") {
          data.cell.styles.textColor = COLORS.danger

          data.cell.styles.fontStyle = "bold"
        }

        if (value === "WARNING") {
          data.cell.styles.textColor = COLORS.warning

          data.cell.styles.fontStyle = "bold"
        }

        if (value === "LOW") {
          data.cell.styles.textColor = COLORS.success

          data.cell.styles.fontStyle = "bold"
        }
      }
    },
  })

  /*
   |--------------------------------------------------------------------------
   | Footer
   |--------------------------------------------------------------------------
   */

  const pageHeight = doc.internal.pageSize.height

  doc.setDrawColor(...COLORS.border)

  doc.line(14, pageHeight - 20, 196, pageHeight - 20)

  doc.setFontSize(9)

  doc.setTextColor(...COLORS.secondary)

  doc.text(
    "Generated by TechBridge Inventory Management System",
    14,
    pageHeight - 12
  )

  doc.text(`Page 1`, 180, pageHeight - 12)

  return doc
}
