import { Inventory } from "@/features/inventory/types/inventory.types"

interface LowStockAlertTemplateProps {
  companyName: string
  products: Inventory[]
}

export const lowStockAlertTemplate = ({
  companyName,
  products,
}: LowStockAlertTemplateProps) => {
  const rows = products
    .map(
      (item) => `
        <tr>
          <td>${item.product}</td>
          <td>${item.stock}</td>
          <td>${item.minimumQuantity}</td>
          <td>${item.reorderQuantity}</td>
          <td>${item.unit}</td>
        </tr>
      `
    )
    .join("")

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body {
            font-family: Arial, sans-serif;
            background: #f4f7fb;
            padding: 32px;
            color: #111827;
          }

          .container {
            max-width: 800px;
            margin: auto;
            background: white;
            border-radius: 16px;
            overflow: hidden;
            box-shadow: 0 10px 30px rgba(0,0,0,0.08);
          }

          .header {
            background: linear-gradient(
              135deg,
              #dc2626,
              #ef4444
            );

            color: white;
            padding: 32px;
          }

          .header h1 {
            margin: 0;
            font-size: 28px;
          }

          .content {
            padding: 32px;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 24px;
          }

          th {
            background: #f3f4f6;
            padding: 14px;
            text-align: left;
            font-size: 13px;
          }

          td {
            padding: 14px;
            border-top: 1px solid #e5e7eb;
            font-size: 14px;
          }

          .footer {
            margin-top: 32px;
            padding-top: 24px;
            border-top: 1px solid #e5e7eb;
            font-size: 13px;
            color: #6b7280;
          }
        </style>
      </head>

      <body>
        <div class="container">

          <div class="header">
            <h1>Low Stock Alert</h1>
          </div>

          <div class="content">

            <p>
              Hi ${companyName},
            </p>

            <p>
              The following products are below minimum stock threshold.
            </p>

            <table>
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Current</th>
                  <th>Minimum</th>
                  <th>Reorder</th>
                  <th>Unit</th>
                </tr>
              </thead>

              <tbody>
                ${rows}
              </tbody>
            </table>

            <div class="footer">
              This is an automated inventory alert generated by your inventory management system.
            </div>

          </div>
        </div>
      </body>
    </html>
  `
}
