export const PURCHASE_REQUEST_ITEM_STATUS = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  ACTION_REQUIRED: "ACTION_REQUIRED",
} as const;

export type PurchaseRequestItemStatus =
  (typeof PURCHASE_REQUEST_ITEM_STATUS)[keyof typeof PURCHASE_REQUEST_ITEM_STATUS];

export const PURCHASE_REQUEST_ITEM_STATUS_LABEL = {
  [PURCHASE_REQUEST_ITEM_STATUS.PENDING_APPROVAL]: "Pending Approval",
  [PURCHASE_REQUEST_ITEM_STATUS.APPROVED]: "Approved",
  [PURCHASE_REQUEST_ITEM_STATUS.REJECTED]: "Rejected",
  [PURCHASE_REQUEST_ITEM_STATUS.ACTION_REQUIRED]: "Action Required",
} as const;